name: (on push) data script check
on:
  push:
    paths:
      - 'myplugins/**'
jobs:
  test-parse:
    name: Data Files
    runs-on: windows-2022
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: install libs
      run: |
        python3 -m pip install Requests
    - name: Get version & set env
      run: python3 res/src/getversion.py
    - name: Download
      run: gh release download -R endless-sky/endless-sky ${{ env.ES_VERSION }} -p ${{ env.RELEASE }}
    - name: Extract & prepare release
      run: |
        mkdir endless-sky
        Expand-Archive ${{ env.RELEASE }} -DestinationPath endless-sky -Force
        rmdir .\myplugins\additional.command.buttons.radial -Recurse -Force
        move .\myplugins .\endless-sky\plugins
    - name: Parse Datafiles
      run: "'.\\endless-sky\\Endless Sky.exe' -p"
      shell: bash
